#!/usr/bin/env node

import {
  copyFileSync,
  existsSync,
  mkdirSync,
  readFileSync,
  readdirSync,
  statSync,
  writeFileSync,
} from "node:fs";
import { dirname, join, relative, resolve } from "node:path";
import { fileURLToPath } from "node:url";
import { spawnSync } from "node:child_process";
import { createRequire } from "node:module";

const skillRoot = resolve(dirname(fileURLToPath(import.meta.url)), "..");
const recipesRoot = join(skillRoot, "assets", "recipes");
const compositionConfigName = "integrations.config.json";
const compositionOwner = "compose-typescript-integrations";
const generatedMarker = `// Generated by ${compositionOwner}. Re-run the compose command to update.`;

function fail(message, code = 1) {
  console.error(`integration-kit: ${message}`);
  process.exit(code);
}

function parseArgs(argv) {
  const options = {
    command: argv[0],
    recipes: [],
    target: process.cwd(),
    force: false,
    install: false,
    dryRun: false,
    json: false,
    live: false,
  };

  for (let index = 1; index < argv.length; index += 1) {
    const value = argv[index];
    if (value === "--target") options.target = argv[++index];
    else if (value === "--force") options.force = true;
    else if (value === "--install") options.install = true;
    else if (value === "--dry-run") options.dryRun = true;
    else if (value === "--json") options.json = true;
    else if (value === "--live") options.live = true;
    else if (value.startsWith("--")) fail(`unknown option ${value}`);
    else options.recipes.push(value);
  }

  options.target = resolve(options.target);
  return options;
}

function readJson(path) {
  try {
    return JSON.parse(readFileSync(path, "utf8"));
  } catch (error) {
    fail(`could not read ${path}: ${error.message}`);
  }
}

function availableRecipes() {
  return ["clerk", "paystack", "r2", "mapbox"].map((id) =>
    readJson(join(recipesRoot, id, "recipe.json")),
  );
}

function packageManager(target) {
  if (existsSync(join(target, "pnpm-lock.yaml"))) return ["pnpm", "add"];
  if (existsSync(join(target, "yarn.lock"))) return ["yarn", "add"];
  if (existsSync(join(target, "bun.lockb")) || existsSync(join(target, "bun.lock"))) {
    return ["bun", "add"];
  }
  return ["npm", "install"];
}

function allDependencies(packageJson) {
  return {
    ...packageJson.dependencies,
    ...packageJson.devDependencies,
  };
}

function sourceFiles(target, limit = 400) {
  const files = [];
  const ignored = new Set([".git", ".next", "build", "coverage", "dist", "node_modules"]);
  const visit = (directory) => {
    if (files.length >= limit || !existsSync(directory)) return;
    for (const entry of readdirSync(directory, { withFileTypes: true })) {
      if (files.length >= limit || ignored.has(entry.name)) continue;
      const path = join(directory, entry.name);
      if (entry.isDirectory()) visit(path);
      else if (/\.(?:[cm]?[jt]sx?|env(?:\.example)?)$/.test(entry.name) && statSync(path).size < 512_000) {
        files.push(path);
      }
    }
  };
  visit(join(target, "src"));
  visit(join(target, "app"));
  visit(join(target, "integrations"));
  for (const name of [".env.example", ".env.local.example"]) {
    if (existsSync(join(target, name))) files.push(join(target, name));
  }
  return files;
}

function sourceIntegrationSignals(target) {
  const signals = [];
  const seen = new Set();
  const add = (integration, evidence, path) => {
    const key = `${integration}:${evidence}:${path}`;
    if (seen.has(key)) return;
    seen.add(key);
    signals.push({ integration, evidence, path: relative(target, path), kind: "source" });
  };
  for (const path of sourceFiles(target)) {
    const content = readFileSync(path, "utf8");
    if (/@clerk\//.test(content)) add("clerk", "Clerk source integration", path);
    else if (/jsonwebtoken|verifyToken\(|OTPService|otp\/verify/i.test(content)) {
      add("clerk", "Existing non-Clerk authentication; plan account and session migration", path);
    }
    if (/api\.paystack\.co|x-paystack-signature|PAYSTACK_SECRET_KEY/.test(content)) {
      add("paystack", "Paystack API, webhook, or configuration path", path);
    }
    if (/r2\.cloudflarestorage\.com|CLOUDFLARE_ACCOUNT_ID|R2_ACCESS_KEY_ID/.test(content)) {
      add("r2", "Cloudflare R2 endpoint or configuration", path);
    } else if (/S3Client|AWS_S3_BUCKET|@aws-sdk\/client-s3/.test(content)) {
      add("r2", "Generic S3-compatible implementation; verify the R2 endpoint", path);
    }
    if (/mapbox-gl|@mapbox\/|MAPBOX_ACCESS_TOKEN/.test(content)) {
      add("mapbox", "Mapbox source integration", path);
    } else if (/GOOGLE_MAPS_API_KEY|Geoapify|maps\.googleapis\.com/.test(content)) {
      add("mapbox", "Existing non-Mapbox location provider; verify migration intent", path);
    }
  }
  return signals;
}

function integrationSignals(packageJson, target) {
  const dependencies = allDependencies(packageJson);
  const signals = [];
  if (Object.keys(dependencies).some((name) => name.startsWith("@clerk/"))) {
    signals.push({ integration: "clerk", evidence: "Clerk SDK dependency", kind: "dependency" });
  }
  if (dependencies["paystack-api"] || dependencies["@paystack/inline-js"]) {
    signals.push({ integration: "paystack", evidence: "Paystack SDK dependency", kind: "dependency" });
  }
  if (dependencies["@aws-sdk/client-s3"]) {
    signals.push({
      integration: "r2",
      evidence: "S3-compatible SDK dependency (could be AWS S3, R2, or another provider)",
      kind: "dependency",
    });
  }
  if (dependencies["mapbox-gl"] || Object.keys(dependencies).some((name) => name.startsWith("@mapbox/"))) {
    signals.push({ integration: "mapbox", evidence: "Mapbox SDK dependency", kind: "dependency" });
  }
  return [...signals, ...sourceIntegrationSignals(target)];
}

function pnpmWorkspaces(target) {
  const path = join(target, "pnpm-workspace.yaml");
  if (!existsSync(path)) return [];
  return readFileSync(path, "utf8")
    .split(/\r?\n/)
    .map((line) => line.match(/^\s*-\s*["']?([^"'#]+?)["']?\s*$/)?.[1])
    .filter(Boolean);
}

function inspectProject(target) {
  const packagePath = join(target, "package.json");
  if (!existsSync(packagePath)) fail(`no package.json found in ${target}`);

  const packageJson = readJson(packagePath);
  const dependencies = allDependencies(packageJson);
  const signals = integrationSignals(packageJson, target);
  const nextRange = dependencies.next;

  const pnpmWorkspacePatterns = pnpmWorkspaces(target);
  if (!nextRange && (packageJson.workspaces || pnpmWorkspacePatterns.length > 0)) {
    const workspaces = pnpmWorkspacePatterns.length > 0
      ? pnpmWorkspacePatterns
      : Array.isArray(packageJson.workspaces)
        ? packageJson.workspaces
        : packageJson.workspaces.packages ?? [];
    return {
      kind: "workspace-root",
      src: "",
      framework: "typescript-workspace-root",
      signals,
      workspaces,
    };
  }

  if (nextRange) {
    const versionMatch = String(nextRange).match(/(\d+)/);
    const nextMajor = versionMatch ? Number(versionMatch[1]) : 16;
    const hasSrcApp = existsSync(join(target, "src", "app"));
    const hasRootApp = existsSync(join(target, "app"));
    if (!hasSrcApp && !hasRootApp) {
      fail("no Next.js App Router directory found (expected src/app or app)");
    }

    return {
      kind: "nextjs-app-router",
      src: hasSrcApp ? "src" : "",
      proxy: nextMajor >= 16 ? "proxy.ts" : "middleware.ts",
      nextMajor,
      framework: `nextjs-${nextMajor}-app-router`,
      signals,
    };
  }

  if (dependencies.vite && dependencies.react && dependencies["react-dom"]) {
    return {
      kind: "vite-react",
      src: "src",
      framework: "vite-react",
      signals,
    };
  }

  if (dependencies.express) {
    return {
      kind: "express",
      src: existsSync(join(target, "src")) ? "src" : "src",
      framework: "express-typescript",
      signals,
    };
  }

  fail("supported targets are Next.js App Router, Vite + React, and Express TypeScript projects");
}

function destinationPath(template, context) {
  return template
    .replaceAll("{{src}}", context.src)
    .replaceAll("{{proxy}}", context.proxy)
    .replace(/^\//, "")
    .replace(/\/+/g, "/");
}

function sameFile(left, right) {
  return existsSync(right) && readFileSync(left).equals(readFileSync(right));
}

function sameText(path, content) {
  return existsSync(path) && readFileSync(path, "utf8") === content;
}

function selectedFromConfig(target) {
  const configPath = join(target, compositionConfigName);
  if (!existsSync(configPath)) {
    fail(`no ${compositionConfigName} found; pass integrations to the compose command first`);
  }
  const config = readJson(configPath);
  if (config.managedBy !== compositionOwner || config.version !== 1) {
    fail(`${compositionConfigName} is not a supported ${compositionOwner} manifest`);
  }
  if (!Array.isArray(config.integrations) || config.integrations.length === 0) {
    fail(`${compositionConfigName} must contain at least one integration`);
  }
  return config.integrations;
}

function compositionConfig(ids) {
  return `${JSON.stringify({ managedBy: compositionOwner, version: 1, integrations: ids }, null, 2)}\n`;
}

function writeCompositionConfig(target, ids, options) {
  const path = join(target, compositionConfigName);
  const content = compositionConfig(ids);
  if (sameText(path, content)) return { path: compositionConfigName, status: "unchanged" };
  const existed = existsSync(path);
  if (existed) {
    const current = readJson(path);
    if (current.managedBy !== compositionOwner && !options.force) {
      fail(`${compositionConfigName} already exists and is not managed by ${compositionOwner}`);
    }
  }
  if (!options.dryRun) writeFileSync(path, content);
  return { path: compositionConfigName, status: existed ? "updated" : "created" };
}

function managedCompositionFile(target, path, content, options) {
  const absolutePath = join(target, path);
  if (sameText(absolutePath, content)) return { path, status: "unchanged" };
  if (existsSync(absolutePath)) {
    const current = readFileSync(absolutePath, "utf8");
    if (!current.startsWith(generatedMarker) && !options.force) {
      return { path, status: "skipped" };
    }
  }
  const status = existsSync(absolutePath) ? "updated" : "created";
  if (!options.dryRun) {
    mkdirSync(dirname(absolutePath), { recursive: true });
    writeFileSync(absolutePath, content);
  }
  return { path, status };
}

function compositionSources(ids, context) {
  const selected = new Set(ids);
  const capabilities = {
    auth: selected.has("clerk") ? "clerk" : null,
    payments: selected.has("paystack") ? "paystack" : null,
    storage: selected.has("r2") ? "r2" : null,
    location: selected.has("mapbox") ? "mapbox" : null,
  };

  const serverExports = [];
  if (selected.has("paystack")) {
    serverExports.push(
      'export { initializePaystackPayment as initializePayment, verifyPaystackPayment as verifyPayment, assertVerifiedPayment } from "./paystack/client";',
      'export { createPaymentReference, toPaystackSubunit as toPaymentSubunit } from "./paystack/money";',
      context.kind === "express"
        ? 'export { createPaystackInitializeHandler as createPaymentInitializeHandler, createPaystackWebhookHandler as createPaymentWebhookHandler, paystackWebhookBody } from "./paystack/express-routes";'
        : 'export { createPaystackInitializeRoute as createPaymentInitializeRoute, createPaystackWebhookRoute as createPaymentWebhookRoute } from "./paystack/next-routes";',
      'export type { InitializePaystackPayment as InitializePayment, PaystackCurrency as PaymentCurrency, VerifiedPaystackTransaction as VerifiedPayment } from "./paystack/client";',
      'export type { PaystackWebhookEvent as PaymentWebhookEvent } from "./paystack/webhook";',
    );
  }
  if (selected.has("r2")) {
    serverExports.push(
      context.kind === "express"
        ? 'export { createR2UploadHandler as createStorageUploadHandler, createR2DownloadHandler as createStorageDownloadHandler } from "./r2/express-routes";'
        : 'export { createR2UploadRoute as createStorageUploadRoute, createR2DownloadRoute as createStorageDownloadRoute } from "./r2/next-routes";',
      'export { putR2Object as putStorageObject, headR2Object as headStorageObject, deleteR2Object as deleteStorageObject, createR2UploadUrl as createStorageUploadUrl, createR2DownloadUrl as createStorageDownloadUrl, createObjectKey as createStorageObjectKey } from "./r2/objects";',
    );
  }

  if (selected.has("clerk") && context.kind === "express") {
    serverExports.push(
      'export { clerkAuthMiddleware, requireClerkAuth, getAuthenticatedUserId } from "./clerk/middleware";',
    );
  }

  const authClient = selected.has("clerk")
    ? 'export { ClerkAuthControls as AuthControls } from "../../components/clerk-auth-controls";'
    : "export {};";
  const locationClient = selected.has("mapbox")
    ? context.kind === "nextjs-app-router"
      ? 'import dynamic from "next/dynamic";\n\nexport type { MapboxLocation as LocationSelection } from "../../components/mapbox-location-picker";\n\nexport const LocationPicker = dynamic(\n  () => import("../../components/mapbox-location-picker").then((module) => module.MapboxLocationPicker),\n  { ssr: false },\n);'
      : 'export { MapboxLocationPicker as LocationPicker } from "../../components/mapbox-location-picker";\nexport type { MapboxLocation as LocationSelection } from "../../components/mapbox-location-picker";'
    : "export {};";
  const storageClient = selected.has("r2")
    ? 'export { uploadToPresignedUrl as uploadToStorageUrl } from "../r2/upload";'
    : "export {};";

  const provider = selected.has("clerk")
    ? `${generatedMarker}\n\nimport { AppAuthProvider } from "./clerk/provider";\nimport type { ReactNode } from "react";\n\nexport function AppIntegrationsProvider({ children }: { children: ReactNode }) {\n  return <AppAuthProvider>{children}</AppAuthProvider>;\n}\n`
    : `${generatedMarker}\n\nimport type { ReactNode } from "react";\n\nexport function AppIntegrationsProvider({ children }: { children: ReactNode }) {\n  return children;\n}\n`;

  const shared = {
    "integrations/capabilities.ts": `${generatedMarker}\n\nexport const integrationCapabilities = ${JSON.stringify(capabilities, null, 2)} as const;\n`,
  };

  if (context.kind === "express") {
    return {
      ...shared,
      "integrations/server.ts": `${generatedMarker}\n\n${serverExports.length ? serverExports.join("\n") : "export {};"}\n`,
    };
  }

  return {
    ...shared,
    "integrations/server.ts": `${generatedMarker}\n\n${context.kind === "nextjs-app-router" && serverExports.length ? serverExports.join("\n") : "export {};"}\n`,
    "integrations/client/auth.ts": `${generatedMarker}\n\n"use client";\n\n${authClient}\n`,
    "integrations/client/location.ts": `${generatedMarker}\n\n"use client";\n\n${locationClient}\n`,
    "integrations/client/storage.ts": `${generatedMarker}\n\n"use client";\n\n${storageClient}\n`,
    "integrations/provider.tsx": provider,
  };
}

function composeProject(target, context, ids, options) {
  const config = writeCompositionConfig(target, ids, options);
  const files = Object.entries(compositionSources(ids, context)).map(([path, content]) =>
    managedCompositionFile(target, destinationPath(`{{src}}/${path}`, context), content, options),
  );
  return { config, files };
}

function ensureEnvExample(target, variables, dryRun) {
  if (variables.length === 0) return { path: null, added: [] };
  const entries = variables.map((entry) =>
    typeof entry === "string" ? { name: entry, value: "" } : entry,
  );
  const envPath = join(target, ".env.example");
  const current = existsSync(envPath) ? readFileSync(envPath, "utf8") : "";
  const present = new Set(
    current
      .split(/\r?\n/)
      .map((line) => line.match(/^([A-Z][A-Z0-9_]*)=/)?.[1])
      .filter(Boolean),
  );
  const added = entries.filter((entry) => !present.has(entry.name));
  if (added.length > 0 && !dryRun) {
    const separator = current.length > 0 && !current.endsWith("\n") ? "\n" : "";
    const block = added.map((entry) => `${entry.name}=${entry.value ?? ""}`).join("\n");
    writeFileSync(envPath, `${current}${separator}${block}\n`);
  }
  return { path: relative(target, envPath), added: added.map((entry) => entry.name) };
}

function installDependencies(target, dependencies) {
  if (dependencies.length === 0) return null;
  const [command, action] = packageManager(target);
  const result = spawnSync(command, [action, ...dependencies], {
    cwd: target,
    stdio: "inherit",
  });
  if (result.error) fail(`could not run ${command}: ${result.error.message}`);
  if (result.status !== 0) fail(`${command} exited with status ${result.status}`);
  return `${command} ${action} ${dependencies.join(" ")}`;
}

function clerkReactCompatibility(target, dependencies) {
  if (!dependencies.includes("@clerk/nextjs")) return [];
  const packageJson = readJson(join(target, "package.json"));
  const minimumPatch = new Map([[0, 3], [1, 4], [2, 3]]);
  const adjustments = [];

  for (const name of ["react", "react-dom"]) {
    const range = packageJson.dependencies?.[name] ?? packageJson.devDependencies?.[name];
    const match = String(range ?? "").match(/19\.(\d+)\.(\d+)/);
    if (!match) continue;
    const minor = Number(match[1]);
    const patch = Number(match[2]);
    const requiredPatch = minimumPatch.get(minor);
    if (requiredPatch !== undefined && patch < requiredPatch) {
      adjustments.push(`${name}@~19.${minor}.${requiredPatch}`);
    }
  }

  return adjustments;
}

function recipeVariant(recipe, context) {
  if (context.kind === "nextjs-app-router") return recipe;
  const variant = recipe.variants?.[context.kind];
  if (!variant) {
    fail(`${recipe.id} does not have a ${context.framework} starter; target the matching web or server workspace`);
  }
  return { ...recipe, ...variant, variants: undefined };
}

function parseEnvFile(path) {
  if (!existsSync(path)) return {};
  const values = {};
  for (const line of readFileSync(path, "utf8").split(/\r?\n/)) {
    const match = line.match(/^\s*([A-Z][A-Z0-9_]*)\s*=\s*(.*)\s*$/);
    if (!match) continue;
    values[match[1]] = match[2].replace(/^(["'])(.*)\1$/, "$2");
  }
  return values;
}

function targetEnvironment(target) {
  const parent = resolve(target, "..");
  const values = {};
  for (const path of [
    join(parent, ".env"),
    join(parent, ".env.local"),
    join(target, ".env"),
    join(target, ".env.local"),
  ]) {
    Object.assign(values, parseEnvFile(path));
  }
  return { ...values, ...process.env };
}

function configuredValue(value) {
  if (!value || !value.trim()) return false;
  return !/(?:your[_-]|change-me|example|replace-me|^<|^\$\{)/i.test(value);
}

const setupGuides = {
  clerk: {
    connector: "Clerk CLI or authenticated Clerk dashboard",
    dashboard: "https://dashboard.clerk.com/",
    steps: [
      "Create or select one Clerk application for both the frontend and backend.",
      "Enable only the requested sign-in methods (for example Google and phone OTP).",
      "Store publishable keys in the web environment and secret keys only in the server secret store.",
      "Run the official Clerk doctor and exercise sign-in, protected API access, and sign-out.",
    ],
  },
  paystack: {
    connector: "Paystack dashboard",
    dashboard: "https://dashboard.paystack.com/#/settings/developer",
    steps: [
      "Start with test keys and store the secret key only on the server.",
      "Register the exact HTTPS webhook URL and retain the raw request body for signature checks.",
      "Run a test card or Ghana mobile-money flow, verify the transaction server-side, and replay the webhook to prove idempotency.",
      "Promote to live keys only after the test path and operational alerts pass.",
    ],
  },
  r2: {
    connector: "Cloudflare connector, Wrangler, or authenticated Cloudflare dashboard",
    dashboard: "https://dash.cloudflare.com/?to=/:account/r2",
    agentActions: [
      "Inspect and adapt the application's existing storage abstraction and real upload/download call path.",
      "Use the Cloudflare connector, Wrangler, or dashboard to reuse or create one private bucket and a bucket-scoped Object Read & Write token.",
      "Store credentials in the established ignored environment or deployment secret store without printing their values.",
      "Configure CORS for the exact frontend origins, methods, and Content-Type header used by browser uploads.",
      "Run project checks and doctor r2 --live against the intended account and bucket.",
    ],
    humanActions: [
      "Complete Cloudflare login, MFA, billing acceptance, or one-time secret entry only when the chosen account flow requires it.",
    ],
    completionCriteria: [
      "The application's real storage path uses the intended R2 bucket with authorization and ownership enforced.",
      "Project typecheck, relevant tests, and build pass.",
      "A live temporary object put/get/delete round trip passes and cleans up its probe object.",
    ],
    steps: [
      "Agent: inspect and adapt the existing storage path instead of adding a parallel implementation.",
      "Agent: create or select the private bucket, configure scoped credentials and exact CORS, and connect deployment secrets.",
      "Human only if blocked: complete Cloudflare login, MFA, billing acceptance, or direct one-time secret entry.",
      "Agent: run project checks and doctor r2 --live; do not call the integration complete until both pass.",
    ],
  },
  mapbox: {
    connector: "Mapbox account dashboard",
    dashboard: "https://account.mapbox.com/access-tokens/",
    steps: [
      "Create a public token with only the scopes needed for maps and search.",
      "Restrict the token to the exact development and production URLs.",
      "Store it in the framework's public environment variable and test search, selection, longitude/latitude order, and denied-token behavior.",
    ],
  },
};

function configurationReport(selected, context, target) {
  const environment = targetEnvironment(target);
  return selected.map((recipe) => {
    const variant = recipeVariant(recipe, context);
    const variables = variant.env.map((entry) => typeof entry === "string" ? entry : entry.name);
    const configured = variables.filter((name) => configuredValue(environment[name]));
    const missing = variables.filter((name) => !configured.includes(name));
    const status = recipe.id === "r2" && context.kind === "vite-react"
      ? "backend-setup-required"
      : missing.length === 0
        ? "locally-configured"
        : "setup-required";
    return {
      id: recipe.id,
      name: recipe.name,
      status,
      configured,
      missing,
      existingSignals: context.signals.filter((signal) => signal.integration === recipe.id),
      guide: setupGuides[recipe.id],
    };
  });
}

async function runR2LiveProbe(target, environment) {
  const required = [
    "CLOUDFLARE_ACCOUNT_ID",
    "R2_ACCESS_KEY_ID",
    "R2_SECRET_ACCESS_KEY",
    "R2_BUCKET",
  ];
  if (required.some((name) => !configuredValue(environment[name]))) {
    return { status: "blocked", detail: "R2 environment is incomplete" };
  }

  const requireFromTarget = createRequire(join(target, "package.json"));
  try {
    const {
      S3Client,
      PutObjectCommand,
      GetObjectCommand,
      DeleteObjectCommand,
    } = requireFromTarget("@aws-sdk/client-s3");
    const client = new S3Client({
      region: "auto",
      endpoint: `https://${environment.CLOUDFLARE_ACCOUNT_ID}.r2.cloudflarestorage.com`,
      credentials: {
        accessKeyId: environment.R2_ACCESS_KEY_ID,
        secretAccessKey: environment.R2_SECRET_ACCESS_KEY,
      },
    });
    const key = `integration-kit-probe/${crypto.randomUUID()}.txt`;
    const body = `integration-kit ${new Date().toISOString()}`;
    try {
      await client.send(new PutObjectCommand({ Bucket: environment.R2_BUCKET, Key: key, Body: body }));
      const downloaded = await client.send(
        new GetObjectCommand({ Bucket: environment.R2_BUCKET, Key: key }),
      );
      const received = await downloaded.Body.transformToString();
      if (received !== body) throw new Error("probe object content did not round-trip");
      return { status: "passed", detail: "temporary object put/get round-trip passed" };
    } finally {
      await client.send(new DeleteObjectCommand({ Bucket: environment.R2_BUCKET, Key: key }));
    }
  } catch (error) {
    return { status: "failed", detail: error instanceof Error ? error.message : String(error) };
  }
}

async function doctorReport(selected, context, target, live) {
  const configuration = configurationReport(selected, context, target);
  const environment = targetEnvironment(target);
  const probes = [];
  for (const item of configuration) {
    if (!live) {
      probes.push({ id: item.id, status: "not-run", detail: "pass --live after configuration" });
    } else if (item.id === "r2") {
      probes.push({ id: item.id, ...(await runR2LiveProbe(target, environment)) });
    } else {
      probes.push({ id: item.id, status: "manual", detail: "follow the provider verification path in the recipe" });
    }
  }
  return { target, framework: context.framework, configuration, probes };
}

function scaffoldRecipe(recipe, target, context, options) {
  const resolvedRecipe = recipeVariant(recipe, context);
  const created = [];
  const unchanged = [];
  const skipped = [];

  for (const entry of resolvedRecipe.files) {
    const source = join(recipesRoot, recipe.id, "template", entry.source);
    const destinationRelative = destinationPath(entry.destination, context);
    const destination = join(target, destinationRelative);
    if (!existsSync(source)) fail(`recipe ${recipe.id} is missing ${entry.source}`);

    if (sameFile(source, destination)) {
      unchanged.push(destinationRelative);
      continue;
    }
    if (existsSync(destination) && !options.force) {
      skipped.push(destinationRelative);
      continue;
    }
    if (!options.dryRun) {
      mkdirSync(dirname(destination), { recursive: true });
      copyFileSync(source, destination);
    }
    created.push(destinationRelative);
  }

  const env = ensureEnvExample(target, resolvedRecipe.env, options.dryRun);
  return {
    id: recipe.id,
    name: recipe.name,
    dependencies: resolvedRecipe.dependencies,
    created,
    unchanged,
    skipped,
    env,
    manualSteps: resolvedRecipe.manualSteps,
  };
}

function printList(recipes, json) {
  if (json) return console.log(JSON.stringify(recipes, null, 2));
  console.log("Available integration starters:\n");
  for (const recipe of recipes) console.log(`  ${recipe.id.padEnd(10)} ${recipe.name}`);
}

function printResult(result) {
  console.log(`\n${result.name}`);
  for (const path of result.created) console.log(`  created    ${path}`);
  for (const path of result.unchanged) console.log(`  unchanged  ${path}`);
  for (const path of result.skipped) console.log(`  skipped    ${path} (use --force to replace)`);
  for (const name of result.env.added) console.log(`  env        ${name}`);
  if (result.dependencies.length > 0) {
    console.log(`  packages   ${result.dependencies.join(" ")}`);
  }
  for (const step of result.manualSteps) console.log(`  next       ${step}`);
}

const options = parseArgs(process.argv.slice(2));
const recipes = availableRecipes();

if (options.command === "list") {
  printList(recipes, options.json);
  process.exit(0);
}

const context = inspectProject(options.target);

if (options.command === "inspect") {
  const inspection = {
    target: options.target,
    framework: context.framework,
    workspaces: context.workspaces ?? [],
    existingIntegrationSignals: context.signals,
  };
  if (options.json) console.log(JSON.stringify(inspection, null, 2));
  else {
    console.log(`Framework: ${inspection.framework}`);
    if (inspection.workspaces.length > 0) {
      console.log("Application workspaces:");
      for (const workspace of inspection.workspaces) console.log(`  ${workspace}`);
    }
    if (inspection.existingIntegrationSignals.length === 0) {
      console.log("Existing integration signals: none");
    } else {
      console.log("Existing integration signals:");
      for (const signal of inspection.existingIntegrationSignals) {
        console.log(`  ${signal.integration.padEnd(10)} ${signal.evidence}`);
      }
    }
  }
  process.exit(0);
}

if (context.kind === "workspace-root") {
  fail("target is a workspace root; run compose against one of the application workspaces shown by inspect");
}

if (
  !["add", "compose", "setup", "doctor"].includes(options.command) ||
  (["add", "setup", "doctor"].includes(options.command) && options.recipes.length === 0)
) {
  fail(
    "usage: scaffold.mjs list | inspect --target DIR | setup <provider>... | doctor <provider>... [--live] | add <provider>... | compose [provider]... [--target DIR] [--install] [--dry-run] [--force] [--json]",
  );
}

const selectedIds = [...new Set(
  options.command === "compose" && options.recipes.length === 0
    ? selectedFromConfig(options.target)
    : options.recipes,
)];
const selected = selectedIds.map((id) => {
  const recipe = recipes.find((item) => item.id === id);
  if (!recipe) fail(`unknown recipe ${id}; run 'scaffold.mjs list'`);
  return recipe;
});

if (options.command === "setup") {
  const report = {
    target: options.target,
    framework: context.framework,
    integrations: configurationReport(selected, context, options.target),
  };
  if (options.json) console.log(JSON.stringify(report, null, 2));
  else {
    console.log(`Setup walkthrough for ${context.framework}`);
    for (const item of report.integrations) {
      console.log(`\n${item.name}: ${item.status}`);
      if (item.configured.length > 0) console.log(`  configured ${item.configured.join(", ")}`);
      if (item.missing.length > 0) console.log(`  missing    ${item.missing.join(", ")}`);
      for (const signal of item.existingSignals) console.log(`  probe      ${signal.evidence}${signal.path ? ` (${signal.path})` : ""}`);
      console.log(`  use        ${item.guide.connector}`);
      console.log(`  open       ${item.guide.dashboard}`);
      if (item.guide.agentActions) {
        item.guide.agentActions.forEach((step) => console.log(`  agent      ${step}`));
        item.guide.humanActions.forEach((step) => console.log(`  human      ${step}`));
        item.guide.completionCriteria.forEach((step) => console.log(`  done when  ${step}`));
      } else {
        item.guide.steps.forEach((step, index) => console.log(`  ${index + 1}. ${step}`));
      }
    }
  }
  process.exit(0);
}

if (options.command === "doctor") {
  const report = await doctorReport(selected, context, options.target, options.live);
  if (options.json) console.log(JSON.stringify(report, null, 2));
  else {
    console.log(`Integration doctor for ${context.framework}`);
    for (const item of report.configuration) {
      console.log(`\n${item.name}: ${item.status}`);
      if (item.missing.length > 0) console.log(`  missing    ${item.missing.join(", ")}`);
      const probe = report.probes.find((candidate) => candidate.id === item.id);
      console.log(`  probe      ${probe.status}: ${probe.detail}`);
    }
  }
  process.exit(0);
}

const composition = options.command === "compose"
  ? composeProject(options.target, context, selectedIds, options)
  : null;
const results = selected.map((recipe) =>
  scaffoldRecipe(recipe, options.target, context, options),
);
const recipeDependencies = results.flatMap((result) => result.dependencies);
const dependencies = [
  ...new Set([
    ...recipeDependencies,
    ...clerkReactCompatibility(options.target, recipeDependencies),
  ]),
];
const installed = options.install && !options.dryRun
  ? installDependencies(options.target, dependencies)
  : null;
const setup = configurationReport(selected, context, options.target);

const output = {
  target: options.target,
  framework: context.framework,
  existingIntegrationSignals: context.signals,
  dryRun: options.dryRun,
  dependencies,
  installed,
  setup,
  composition,
  results,
};

if (options.json) console.log(JSON.stringify(output, null, 2));
else {
  for (const signal of context.signals) {
    console.log(`\nPreserved existing signal\n  ${signal.integration.padEnd(10)} ${signal.evidence}${signal.path ? ` (${signal.path})` : ""}`);
  }
  if (composition) {
    console.log(`\nComposition manifest\n  ${composition.config.status.padEnd(10)} ${composition.config.path}`);
    for (const file of composition.files) console.log(`  ${file.status.padEnd(10)} ${file.path}`);
  }
  for (const result of results) printResult(result);
  console.log("\nSetup walkthrough");
  for (const item of setup) {
    console.log(`\n  ${item.name}: ${item.status}`);
    if (item.missing.length > 0) console.log(`  missing    ${item.missing.join(", ")}`);
    for (const signal of item.existingSignals) console.log(`  inspect    ${signal.evidence}${signal.path ? ` (${signal.path})` : ""}`);
    console.log(`  use        ${item.guide.connector}`);
    console.log(`  open       ${item.guide.dashboard}`);
    if (item.guide.agentActions) {
      item.guide.agentActions.forEach((step) => console.log(`  agent      ${step}`));
      item.guide.humanActions.forEach((step) => console.log(`  human      ${step}`));
      item.guide.completionCriteria.forEach((step) => console.log(`  done when  ${step}`));
    } else {
      item.guide.steps.forEach((step, index) => console.log(`  ${index + 1}. ${step}`));
    }
  }
  console.log(`\nRun diagnostics:\n  node ${relative(process.cwd(), fileURLToPath(import.meta.url))} doctor ${selectedIds.join(" ")} --target ${relative(process.cwd(), options.target) || "."}`);
  if (!options.install && dependencies.length > 0) {
    const [command, action] = packageManager(options.target);
    console.log(`\nInstall dependencies:\n  ${command} ${action} ${dependencies.join(" ")}`);
  }
  if (results.some((result) => result.skipped.length > 0)) {
    console.log("\nExisting files were preserved. Ask the agent to merge them deliberately.");
  }
}
