#!/usr/bin/env node

import { existsSync, mkdirSync, readFileSync, writeFileSync, copyFileSync } from "node:fs";
import { dirname, join, relative, resolve } from "node:path";
import { fileURLToPath } from "node:url";
import { spawnSync } from "node:child_process";

const skillRoot = resolve(dirname(fileURLToPath(import.meta.url)), "..");
const recipesRoot = join(skillRoot, "assets", "recipes");
const compositionConfigName = "integrations.config.json";
const compositionOwner = "compose-typescript-integrations";
const generatedMarker = `// Generated by ${compositionOwner}. Re-run the compose command to update.`;

function fail(message, code = 1) {
  console.error(`integration-kit: ${message}`);
  process.exit(code);
}

function parseArgs(argv) {
  const options = {
    command: argv[0],
    recipes: [],
    target: process.cwd(),
    force: false,
    install: false,
    dryRun: false,
    json: false,
  };

  for (let index = 1; index < argv.length; index += 1) {
    const value = argv[index];
    if (value === "--target") options.target = argv[++index];
    else if (value === "--force") options.force = true;
    else if (value === "--install") options.install = true;
    else if (value === "--dry-run") options.dryRun = true;
    else if (value === "--json") options.json = true;
    else if (value.startsWith("--")) fail(`unknown option ${value}`);
    else options.recipes.push(value);
  }

  options.target = resolve(options.target);
  return options;
}

function readJson(path) {
  try {
    return JSON.parse(readFileSync(path, "utf8"));
  } catch (error) {
    fail(`could not read ${path}: ${error.message}`);
  }
}

function availableRecipes() {
  return ["clerk", "paystack", "r2", "mapbox"].map((id) =>
    readJson(join(recipesRoot, id, "recipe.json")),
  );
}

function packageManager(target) {
  if (existsSync(join(target, "pnpm-lock.yaml"))) return ["pnpm", "add"];
  if (existsSync(join(target, "yarn.lock"))) return ["yarn", "add"];
  if (existsSync(join(target, "bun.lockb")) || existsSync(join(target, "bun.lock"))) {
    return ["bun", "add"];
  }
  return ["npm", "install"];
}

function inspectNextProject(target) {
  const packagePath = join(target, "package.json");
  if (!existsSync(packagePath)) fail(`no package.json found in ${target}`);

  const packageJson = readJson(packagePath);
  const nextRange = packageJson.dependencies?.next ?? packageJson.devDependencies?.next;
  if (!nextRange) fail("the first release supports Next.js App Router projects only");

  const versionMatch = String(nextRange).match(/(\d+)/);
  const nextMajor = versionMatch ? Number(versionMatch[1]) : 16;
  const hasSrcApp = existsSync(join(target, "src", "app"));
  const hasRootApp = existsSync(join(target, "app"));
  if (!hasSrcApp && !hasRootApp) {
    fail("no Next.js App Router directory found (expected src/app or app)");
  }

  return {
    src: hasSrcApp ? "src" : "",
    proxy: nextMajor >= 16 ? "proxy.ts" : "middleware.ts",
    nextMajor,
  };
}

function destinationPath(template, context) {
  return template
    .replaceAll("{{src}}", context.src)
    .replaceAll("{{proxy}}", context.proxy)
    .replace(/^\//, "")
    .replace(/\/+/g, "/");
}

function sameFile(left, right) {
  return existsSync(right) && readFileSync(left).equals(readFileSync(right));
}

function sameText(path, content) {
  return existsSync(path) && readFileSync(path, "utf8") === content;
}

function selectedFromConfig(target) {
  const configPath = join(target, compositionConfigName);
  if (!existsSync(configPath)) {
    fail(`no ${compositionConfigName} found; pass integrations to the compose command first`);
  }
  const config = readJson(configPath);
  if (config.managedBy !== compositionOwner || config.version !== 1) {
    fail(`${compositionConfigName} is not a supported ${compositionOwner} manifest`);
  }
  if (!Array.isArray(config.integrations) || config.integrations.length === 0) {
    fail(`${compositionConfigName} must contain at least one integration`);
  }
  return config.integrations;
}

function compositionConfig(ids) {
  return `${JSON.stringify({ managedBy: compositionOwner, version: 1, integrations: ids }, null, 2)}\n`;
}

function writeCompositionConfig(target, ids, options) {
  const path = join(target, compositionConfigName);
  const content = compositionConfig(ids);
  if (sameText(path, content)) return { path: compositionConfigName, status: "unchanged" };
  const existed = existsSync(path);
  if (existed) {
    const current = readJson(path);
    if (current.managedBy !== compositionOwner && !options.force) {
      fail(`${compositionConfigName} already exists and is not managed by ${compositionOwner}`);
    }
  }
  if (!options.dryRun) writeFileSync(path, content);
  return { path: compositionConfigName, status: existed ? "updated" : "created" };
}

function managedCompositionFile(target, path, content, options) {
  const absolutePath = join(target, path);
  if (sameText(absolutePath, content)) return { path, status: "unchanged" };
  if (existsSync(absolutePath)) {
    const current = readFileSync(absolutePath, "utf8");
    if (!current.startsWith(generatedMarker) && !options.force) {
      return { path, status: "skipped" };
    }
  }
  const status = existsSync(absolutePath) ? "updated" : "created";
  if (!options.dryRun) {
    mkdirSync(dirname(absolutePath), { recursive: true });
    writeFileSync(absolutePath, content);
  }
  return { path, status };
}

function compositionSources(ids) {
  const selected = new Set(ids);
  const capabilities = {
    auth: selected.has("clerk") ? "clerk" : null,
    payments: selected.has("paystack") ? "paystack" : null,
    storage: selected.has("r2") ? "r2" : null,
    location: selected.has("mapbox") ? "mapbox" : null,
  };

  const serverExports = [];
  if (selected.has("paystack")) {
    serverExports.push(
      'export { initializePaystackPayment as initializePayment, verifyPaystackPayment as verifyPayment, assertVerifiedPayment } from "./paystack/client";',
      'export { createPaymentReference, toPaystackSubunit as toPaymentSubunit } from "./paystack/money";',
      'export { createPaystackInitializeRoute as createPaymentInitializeRoute, createPaystackWebhookRoute as createPaymentWebhookRoute } from "./paystack/next-routes";',
      'export type { InitializePaystackPayment as InitializePayment, PaystackCurrency as PaymentCurrency, VerifiedPaystackTransaction as VerifiedPayment } from "./paystack/client";',
      'export type { PaystackWebhookEvent as PaymentWebhookEvent } from "./paystack/webhook";',
    );
  }
  if (selected.has("r2")) {
    serverExports.push(
      'export { createR2UploadRoute as createStorageUploadRoute, createR2DownloadRoute as createStorageDownloadRoute } from "./r2/next-routes";',
      'export { putR2Object as putStorageObject, headR2Object as headStorageObject, deleteR2Object as deleteStorageObject, createR2UploadUrl as createStorageUploadUrl, createR2DownloadUrl as createStorageDownloadUrl, createObjectKey as createStorageObjectKey } from "./r2/objects";',
    );
  }

  const authClient = selected.has("clerk")
    ? 'export { ClerkAuthControls as AuthControls } from "../../components/clerk-auth-controls";'
    : "export {};";
  const locationClient = selected.has("mapbox")
    ? 'import dynamic from "next/dynamic";\n\nexport type { MapboxLocation as LocationSelection } from "../../components/mapbox-location-picker";\n\nexport const LocationPicker = dynamic(\n  () => import("../../components/mapbox-location-picker").then((module) => module.MapboxLocationPicker),\n  { ssr: false },\n);'
    : "export {};";
  const storageClient = selected.has("r2")
    ? 'export { uploadToPresignedUrl as uploadToStorageUrl } from "../r2/upload";'
    : "export {};";

  const provider = selected.has("clerk")
    ? `${generatedMarker}\n\nimport { AppAuthProvider } from "./clerk/provider";\nimport type { ReactNode } from "react";\n\nexport function AppIntegrationsProvider({ children }: { children: ReactNode }) {\n  return <AppAuthProvider>{children}</AppAuthProvider>;\n}\n`
    : `${generatedMarker}\n\nimport type { ReactNode } from "react";\n\nexport function AppIntegrationsProvider({ children }: { children: ReactNode }) {\n  return children;\n}\n`;

  return {
    "integrations/capabilities.ts": `${generatedMarker}\n\nexport const integrationCapabilities = ${JSON.stringify(capabilities, null, 2)} as const;\n`,
    "integrations/server.ts": `${generatedMarker}\n\n${serverExports.length ? serverExports.join("\n") : "export {};"}\n`,
    "integrations/client/auth.ts": `${generatedMarker}\n\n"use client";\n\n${authClient}\n`,
    "integrations/client/location.ts": `${generatedMarker}\n\n"use client";\n\n${locationClient}\n`,
    "integrations/client/storage.ts": `${generatedMarker}\n\n"use client";\n\n${storageClient}\n`,
    "integrations/provider.tsx": provider,
  };
}

function composeProject(target, context, ids, options) {
  const config = writeCompositionConfig(target, ids, options);
  const files = Object.entries(compositionSources(ids)).map(([path, content]) =>
    managedCompositionFile(target, destinationPath(`{{src}}/${path}`, context), content, options),
  );
  return { config, files };
}

function ensureEnvExample(target, variables, dryRun) {
  if (variables.length === 0) return { path: null, added: [] };
  const entries = variables.map((entry) =>
    typeof entry === "string" ? { name: entry, value: "" } : entry,
  );
  const envPath = join(target, ".env.example");
  const current = existsSync(envPath) ? readFileSync(envPath, "utf8") : "";
  const present = new Set(
    current
      .split(/\r?\n/)
      .map((line) => line.match(/^([A-Z][A-Z0-9_]*)=/)?.[1])
      .filter(Boolean),
  );
  const added = entries.filter((entry) => !present.has(entry.name));
  if (added.length > 0 && !dryRun) {
    const separator = current.length > 0 && !current.endsWith("\n") ? "\n" : "";
    const block = added.map((entry) => `${entry.name}=${entry.value ?? ""}`).join("\n");
    writeFileSync(envPath, `${current}${separator}${block}\n`);
  }
  return { path: relative(target, envPath), added: added.map((entry) => entry.name) };
}

function installDependencies(target, dependencies) {
  if (dependencies.length === 0) return null;
  const [command, action] = packageManager(target);
  const result = spawnSync(command, [action, ...dependencies], {
    cwd: target,
    stdio: "inherit",
  });
  if (result.error) fail(`could not run ${command}: ${result.error.message}`);
  if (result.status !== 0) fail(`${command} exited with status ${result.status}`);
  return `${command} ${action} ${dependencies.join(" ")}`;
}

function clerkReactCompatibility(target, dependencies) {
  if (!dependencies.includes("@clerk/nextjs")) return [];
  const packageJson = readJson(join(target, "package.json"));
  const minimumPatch = new Map([[0, 3], [1, 4], [2, 3]]);
  const adjustments = [];

  for (const name of ["react", "react-dom"]) {
    const range = packageJson.dependencies?.[name] ?? packageJson.devDependencies?.[name];
    const match = String(range ?? "").match(/19\.(\d+)\.(\d+)/);
    if (!match) continue;
    const minor = Number(match[1]);
    const patch = Number(match[2]);
    const requiredPatch = minimumPatch.get(minor);
    if (requiredPatch !== undefined && patch < requiredPatch) {
      adjustments.push(`${name}@~19.${minor}.${requiredPatch}`);
    }
  }

  return adjustments;
}

function scaffoldRecipe(recipe, target, context, options) {
  const created = [];
  const unchanged = [];
  const skipped = [];

  for (const entry of recipe.files) {
    const source = join(recipesRoot, recipe.id, "template", entry.source);
    const destinationRelative = destinationPath(entry.destination, context);
    const destination = join(target, destinationRelative);
    if (!existsSync(source)) fail(`recipe ${recipe.id} is missing ${entry.source}`);

    if (sameFile(source, destination)) {
      unchanged.push(destinationRelative);
      continue;
    }
    if (existsSync(destination) && !options.force) {
      skipped.push(destinationRelative);
      continue;
    }
    if (!options.dryRun) {
      mkdirSync(dirname(destination), { recursive: true });
      copyFileSync(source, destination);
    }
    created.push(destinationRelative);
  }

  const env = ensureEnvExample(target, recipe.env, options.dryRun);
  return {
    id: recipe.id,
    name: recipe.name,
    dependencies: recipe.dependencies,
    created,
    unchanged,
    skipped,
    env,
    manualSteps: recipe.manualSteps,
  };
}

function printList(recipes, json) {
  if (json) return console.log(JSON.stringify(recipes, null, 2));
  console.log("Available integration starters:\n");
  for (const recipe of recipes) console.log(`  ${recipe.id.padEnd(10)} ${recipe.name}`);
}

function printResult(result) {
  console.log(`\n${result.name}`);
  for (const path of result.created) console.log(`  created    ${path}`);
  for (const path of result.unchanged) console.log(`  unchanged  ${path}`);
  for (const path of result.skipped) console.log(`  skipped    ${path} (use --force to replace)`);
  for (const name of result.env.added) console.log(`  env        ${name}`);
  if (result.dependencies.length > 0) {
    console.log(`  packages   ${result.dependencies.join(" ")}`);
  }
  for (const step of result.manualSteps) console.log(`  next       ${step}`);
}

const options = parseArgs(process.argv.slice(2));
const recipes = availableRecipes();

if (options.command === "list") {
  printList(recipes, options.json);
  process.exit(0);
}

if (!["add", "compose"].includes(options.command) || (options.command === "add" && options.recipes.length === 0)) {
  fail(
    "usage: scaffold.mjs list | add <clerk|paystack|r2|mapbox>... | compose [clerk|paystack|r2|mapbox]... [--target DIR] [--install] [--dry-run] [--force] [--json]",
  );
}

const selectedIds = [...new Set(
  options.command === "compose" && options.recipes.length === 0
    ? selectedFromConfig(options.target)
    : options.recipes,
)];
const selected = selectedIds.map((id) => {
  const recipe = recipes.find((item) => item.id === id);
  if (!recipe) fail(`unknown recipe ${id}; run 'scaffold.mjs list'`);
  return recipe;
});
const context = inspectNextProject(options.target);
const composition = options.command === "compose"
  ? composeProject(options.target, context, selectedIds, options)
  : null;
const results = selected.map((recipe) =>
  scaffoldRecipe(recipe, options.target, context, options),
);
const recipeDependencies = results.flatMap((result) => result.dependencies);
const dependencies = [
  ...new Set([
    ...recipeDependencies,
    ...clerkReactCompatibility(options.target, recipeDependencies),
  ]),
];
const installed = options.install && !options.dryRun
  ? installDependencies(options.target, dependencies)
  : null;

const output = {
  target: options.target,
  framework: `nextjs-${context.nextMajor}-app-router`,
  dryRun: options.dryRun,
  dependencies,
  installed,
  composition,
  results,
};

if (options.json) console.log(JSON.stringify(output, null, 2));
else {
  if (composition) {
    console.log(`\nComposition manifest\n  ${composition.config.status.padEnd(10)} ${composition.config.path}`);
    for (const file of composition.files) console.log(`  ${file.status.padEnd(10)} ${file.path}`);
  }
  for (const result of results) printResult(result);
  if (!options.install && dependencies.length > 0) {
    const [command, action] = packageManager(options.target);
    console.log(`\nInstall dependencies:\n  ${command} ${action} ${dependencies.join(" ")}`);
  }
  if (results.some((result) => result.skipped.length > 0)) {
    console.log("\nExisting files were preserved. Ask the agent to merge them deliberately.");
  }
}
